language: python

cache:
  pip: true
  directories:
    - .venv

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install poetry
  - poetry config virtualenvs.in-project true

install:
  - poetry install

script: poetry run task test
