version: 2.1
jobs:
  codecov:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Install poetry
          command: 'pip install poetry'
      - run:
          name: Install project
          command: 'poetry install'
      - run:
          name: Run coverage
          command: 'poetry run task cov'
      - run:
          name: Upload coverage
          command: 'bash <(curl -s https://codecov.io/bash)'