version: 2.1

orbs:
  poetry: frameio/poetry@0.17.3

workflows:
  codecov:
    jobs:
      - poetry/install
      - poetry/shell:
          args: task cov && bash <(curl -s https://codecov.io/bash)
          requires:
            - poetry/install
