version: 2.1

orbs:
  poetry: frameio/poetry@0.17.3
executors:
  python-tres-ocho:
    docker:
      - image: circleci/python:3.8

workflows:
  codecov:
    jobs:
      - poetry/install:
          executor: python-tres-ocho
      - poetry/shell:
          executor: python-tres-ocho
          args: task cov && bash <(curl -s https://codecov.io/bash)
          requires:
            - poetry/install
