version: 2.1

orbs:
  poetry: frameio/poetry@0.17.3

workflows:
  ci:
    jobs:
      - poetry/install
      - poetry/shell:
          args: task test
          requires:
            - poetry/install
