name: Deploy to heroku
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "que-vemos"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: heroku git:remote -a que-vemos && git push heroku master