name: Deploy to Digital Ocean
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl registry login
      - run: docker image build . -f Dockerfile.web -t que-vemos
      - run: docker tag que-vemos registry.digitalocean.com/que-vemos/que-vemos
      - run: docker push registry.digitalocean.com/que-vemos/que-vemos
