name: que-vemos QA
on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v3
      - run: poetry install
      - run: poetry run task lint

  push-test-container-to-GPR:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Docker Images to GPR
        uses: machine-learning-apps/gpr-docker-publish@v1.3
        with:
          IMAGE_NAME: "que-vemos"
          TAG: "que-vemos"
          DOCKERFILE_PATH: "Dockerfile"
          BUILD_CONTEXT: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -t -v `pwd`:/test alexmenor/que-vemos
