name: que-vemos QA
on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v3
      - run: poetry install
      - run: poetry run task lint

  push-test-container-to-GPR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Container Registry
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Push
        run: docker build -t $IMAGE_PATH && docker push $IMAGE_PATH
        env:
          IMAGE_PATH: ghcr.io/AlexMenor/que-vemos-test-env:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login Container Registry
        run: echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - run: docker run -t -v `pwd`:/test $IMAGE_PATH
        env:
          IMAGE_PATH: ghcr.io/AlexMenor/que-vemos-test-env:latest
